routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');
Route::resource('user', 'UserController');
Route::resource('task', 'TaskController');
Route::get('task/create/{id}', 'TaskController@create');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
	public $timestamps = false;
	
    public function allWorkers() {
    	return $this->belongsToMany('App\User', 'rel_projects_users', 'project_id', 'user_id');
    }

    public function allTasks() {
    	return $this->hasMany('App\Task');
    }

    public function allMilestones() {
    	return $this->hasMany('App\Milestone', 'rel_projects_milestones', 'project_id', 'milestone_id');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('project.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //  validation
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
        ]);

        $project = new \App\Project;
        $project->title = $request->title;
        $project->description = $request->description;
        $project->start_date = $request->start_date;
        $project->end_date = $request->end_date;
        $project->creation_date = \Carbon\Carbon::now()->format('d.m.Y');
        $project->author_id = \Auth::user()->id;
        $project->save();
        //  IMPORTANT - first save, else there is no project-id to attach our users to!!
        $project->allWorkers()->attach($request->employee);

        return redirect('project');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = \App\Project::find($id);
        return view('project.single')->with('project', $project);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = \App\Project::find($id);
        return view('project.edit')->with('project', $project);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //  validation
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
        ]);

        $project = \App\Project::find($id);
        $project->title = $request->title;
        $project->description = $request->description;
        $project->start_date = $request->start_date;
        $project->end_date = $request->end_date;
        $project->creation_date = \Carbon\Carbon::now()->format('d.m.Y');
        $project->author_id = \Auth::user()->id;
        $project->save();
        //  IMPORTANT - first save, else there is no project-id to attach our users to!!
        $project->allWorkers()->detach();
        $project->allWorkers()->attach($request->employee);

        $project->save();
        return redirect('project');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = \App\Project::find($id);
        $project->allWorkers()->detach();
        $project->allMilestones()->detach();
        $project->allTasks()->detach();
        $project->delete();
        return redirect('project');
    }
}

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Project Create</div>
                 <div class="form-group">
                    <form action="../project" method="post" id="createform">
                        <input type="text" placeholder="Titel" id="title" name="title">
                        <input type="text" placeholder="Startdatum" id="start_date" data-provide="datepicker" name="start_date">
                        <input type="text" placeholder="Enddatum" id="end_date" data-provide="datepicker" name="end_date">
                        <textarea type="text" rows="10" name="description" placeholder="Beschreibung"></textarea>
                        {{ csrf_field() }}
                        @foreach(\App\User::all() as $user)
                            <span><input type="checkbox" name="employee[]" value="{{$user->id}}">{{$user->name}}</span>
                        @endforeach
                        <button type="submit">Speichern</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">

    form {
        width: 50%;
        margin: auto;
    }

    form * {
        width: 100%;
        margin-top: 10px !important;
        margin-bottom: 10px !important;
    }

    #similar {
        position: absolute;
        left: 0px;
        bottom: 0px;
        width: 400px;
        height: 750px;
        background-color: darkgrey;
    }
</style>

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Project Create</div>
                 <div class="form-group">
                    <form action="../../project/{{$project->id}}" method="post" id="createform">
                        <input name="_method" type="hidden" value="PUT">
                        <input type="text" placeholder="Titel" id="title" name="title" value="{{$project->title}}">
                        <input type="text" placeholder="Startdatum" id="start_date" data-provide="datepicker" name="start_date" value="{{$project->start_date}}">
                        <input type="text" placeholder="Enddatum" id="end_date" data-provide="datepicker" name="end_date" value="{{$project->end_date}}">
                        <textarea type="text" rows="10" name="description" placeholder="Beschreibung">{{$project->description}}</textarea>
                        {{ csrf_field() }}
                        @foreach(\App\User::all() as $user)
                            <span><input type="checkbox" name="employee[]" value="{{$user->id}}"@if(\App\Project::find($project->id)->allWorkers()->get()->contains($user->id)) checked @endif>{{$user->name}}</span>
                        @endforeach
                        <button type="submit">Speichern</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">

    form {
        width: 50%;
        margin: auto;
    }

    form * {
        width: 100%;
        margin-top: 10px !important;
        margin-bottom: 10px !important;
    }

    #similar {
        position: absolute;
        left: 0px;
        bottom: 0px;
        width: 400px;
        height: 750px;
        background-color: darkgrey;
    }
</style>

resources/views/project/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Projektliste<span class="pull-right"><a href="project/create"><i class="fa fa-calendar-plus-o"></i> erstellen</a></span></div>
                <div class="panel-body">
                    @foreach(\App\Project::all() as $project)
                    <a href="project/{{$project->id}}">{{$project->title}}</a></br>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/project/single.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="panel-heading">{{$project->title}}<span class="pull-right">
        <form class="pull-right" action="{{ route('project.destroy', $project->id) }}" method="POST">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <button><i class="fa fa-trash-o"></i> löschen</button>
        </form> 
        <a href="../task/create/{{$project->id}}"><i class="fa fa-plus"></i>aufgabe hinzufügen</a> <a href="../project/{{$project->id}}/edit"><i class="fa fa-pencil"></i>projekt editieren</a>
    </span></div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                	<p>Name: {{$project->title}}</p>
                	<p>Beschreibung: {{$project->description}}</p>
                	<p>Start: {{$project->start_date}}</p>
                	<p>Ende: {{$project->end_date}}</p>
                	<p>Mitarbeiter:</p>
                    <p>
                	@foreach($project->allWorkers()->get() as $worker)
                		<a href="../user/{{$worker->id}}">{{$worker->name}}</a></br>
                	@endforeach
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>Aufgaben:</p>
                    @foreach($project->allTasks()->get() as $task)
                        <p><a class="focus" data-id="{{$task->id}}" title="Auf Timeline fokussieren"><i class="fa fa-eye"></i></a> <a href="../task/{{$task->id}}">{{$task->title}}</a></p>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>Name: {{$project->title}}</p>
                    <p>Beschreibung: {{$project->description}}</p>
                    <p>Start: {{$project->start_date}}</p>
                    <p>Ende: {{$project->end_date}}</p>
                    <p>Mitarbeiter:</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="timeline_controls">
    <a id="fit">[fit timeline]</a>
</div>
<div id="timeline"></div>
@endsection
@section('page-js-script')
<script type="text/javascript">
    jQuery(document).ready(function(){
        var items = new vis.DataSet([
            @foreach($project->allTasks()->get() as $task)
            {id: {{$task->id}}, content: '{{$task->title}}', start: new Date("{{$task->start_date}}".split(".")[2], "{{$task->start_date}}".split(".")[1]-1, "{{$task->start_date}}".split(".")[0]), end: new Date("{{$task->end_date}}".split(".")[2], "{{$task->end_date}}".split(".")[1]-1, "{{$task->end_date}}".split(".")[0]), title: "<p>{{$task->description}}</p><p>Start: {{$task->start_date}}</p><p>Ende: {{$task->end_date}}</p><p>Sachbearbeiter:{{\App\User::find($task->user_id)->name}}</p>" },
            @endforeach
            {id: 61, content: 'Milestone', start: '2017-11-27', type: 'point'}
        ]);
        var container = document.getElementById("timeline")
        var options = {
            height: "300px",
            locale: "de",
            editable: {
                add: true,
                updateTime: true,
                overrideItems: true,
                updateGroup: true
            },
            //  Enable Tooltips
            tooltip: {
                followMouse: true,
                overflowMethod: 'cap'
            },
            //  Snap to full days
            snap: function(date, scale, step) {
                var clone = new Date(date.valueOf());
                scale = 'day';
                step = 2;
                return vis.timeline.TimeStep.snap(clone, scale, step);
            },
            onMove: function(item, callback) {
                var d = new Date(item.start);
            }
        };
        var timeline = new vis.Timeline(container, items, options);

        jQuery("#fit").click(function() {
            timeline.fit();
        });
        jQuery(".focus").click(function() {
            timeline.focus(jQuery(this).data("id"));
        });
    });
</script>
@endsection
<style type="text/css">
    table {
        width: 100%;
    }
    table tr td {
        padding: 5px;
        border: 1px solid rgba(0, 0, 0, .1);
    }
    button {
        background:none;
        border:none;
        margin:0;
        padding:0;
        color: #3097D1 !important;
        cursor: pointer;
    }

    button:hover {
        text-decoration: underline;
        color: #216a94 !important;
    }
</style>