routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController');
Route::resource('user', 'UserController');
Route::resource('task', 'TaskController');
Route::get('task/create/{id}', 'TaskController@create');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("user.list");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("user.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->passwort),
        ]);
        return view("user.list");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view("user.single")->with("user", $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = \App\User::find($id);
        $user->delete();
        return redirect('user');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Project Create</div>
                 <div class="form-group">
                    <form action="../user" method="post" id="createform">
                        <input type="text" placeholder="Name" id="name" name="name">
                        <input type="text" placeholder="E-Mail" id="email" name="email">
                        <input type="text" placeholder="Passwort" id="passwort" name="passwort">
                        {{ csrf_field() }}
                        <button type="submit">Speichern</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">

    form {
        width: 50%;
        margin: auto;
    }

    form * {
        width: 100%;
        margin-top: 10px !important;
        margin-bottom: 10px !important;
    }

    #similar {
        position: absolute;
        left: 0px;
        bottom: 0px;
        width: 400px;
        height: 750px;
        background-color: darkgrey;
    }
</style>

resources/views/user/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">User List<span class="pull-right"><a href="user/create">[create]</a></span></div>
                <div class="panel-body">
                    @foreach(\App\User::all() as $user)
                    <span><a href="user/{{$user->id}}">{{$user->name}}</a></span><br/>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/single.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            	<div class="panel-heading">
            		<form class="pull-right" action="{{ route('user.destroy', $user->id) }}" method="POST">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button>[delete]</button>
                </form>
            	</div>
                <div class="panel-body">{{$user->name}}</div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">
    table {
        width: 100%;
    }
    table tr td {
        padding: 5px;
        border: 1px solid rgba(0, 0, 0, .1);
    }
    button {
        background:none;
        border:none;
        margin:0;
        padding:0;
        color: #3097D1 !important;
        cursor: pointer;
    }

    button:hover {
        text-decoration: underline;
        color: #216a94 !important;
    }
</style>